environment:
  matrix:
    - PYTHON: "C:\\Python27"
      TOX_ENV: "py27"

    - PYTHON: "C:\\Python34"
      TOX_ENV: "py34"

    - PYTHON: "C:\\Python36"
      TOX_ENV: "py36"

install:
  - "%PYTHON%/Scripts/pip install tox"
  - "%PYTHON%/Scripts/pip install wheel"

build: false  # Not a C# project, build stuff at the test step instead.

test_script:
  - "%PYTHON%/Scripts/tox -e %TOX_ENV%"

on_success:
    # Report coverage results to codecov.io
    # and export tox environment variables
    - "%PYTHON%/Scripts/pip install codecov"
    - set OS=WINDOWS
    - "%PYTHON%/Scripts/codecov -e TOX_ENV OS"
